---
- hosts: harbor
  vars:
  - cpath: /data/
  - version: v1.5.3
  tasks: 
  - name: Ensure Gluster volume is mounted.
    mount:
      path: /data/harborHA
      src: "{{ gfs_ip }}:/gv0"
      fstype: glusterfs
      opts: "defaults,_netdev"
      state: mounted
    tags:
      - mount

  - name: unarchive harbor
    unarchive:
      src: files/harbor-offline-installer-{{ version }}.tgz
      dest: '{{ cpath }}'
    when: inventory_hostname == ansible_play_batch[0]
    tags: 
      - scp

  - name: copy sqlfile
    copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    with_items:
    - { src: 'files/registry.sql', dest: '{{ cpath }}' }
    when: inventory_hostname == ansible_play_batch[0]

  - name: load data
    shell: |
      mysql -uroot -p'{{ pxc_password }}' -e "set global pxc_strict_mode=PERMISSIVE;"
      mysql -uroot -p'{{ pxc_password }}' < {{ cpath }}/registry.sql
      mysql -uroot -p'{{ pxc_password }}' -e "set global pxc_strict_mode=ENFORCING;"
    when: inventory_hostname == ansible_play_batch[0]
