---
- hosts: glusterfs
  vars:
    path: /data/glusterfs/gv0
  tasks: 
  - name: make gfs dir
    file:
      path: '{{ item }}'
      state: directory
      mode: 0755
    with_items:
      - '{{ path }}'

  - name: install GlusterFS
    yum: 
      name: glusterfs-server
      state: present

  - name: enable glusterd
    systemd:
      name: glusterd
      state: started
      enabled: yes

  - name: create gluster volume
    gluster_volume:
      state: present
      name: gv0
      bricks: /data/glusterfs/gv0
      rebalance: yes
      cluster:
        - 192.168.92.138
        - 192.168.92.143
        - 192.168.92.144
      force: yes
    run_once: true
