---
- hosts: glusterfs
  tasks:
  - name: shutdown keepalived
    systemd:
      name: keepalived
      state: stopped
      enabled: no
    ignore_errors: yes
    tags:
      - keepalived

  - name: remove keepalived
    yum:
      name: keepalived
      state: absent
    tags:
      - keepalived

