---
- hosts: pxc
  tasks:
  - name: shutdown PXC
    systemd:
      name: mysql
      state: stopped
      enabled: no
    ignore_errors: yes

  - name: remove PXC
    yum: 
      name: Percona-XtraDB-Cluster*
      state: absent
    tags:
      - clean

  - name: remove PXC dir
    file:
      path: '{{ item }}'
      state: absent
    with_items:
      - '{{ pxc_dir }}'
      - /var/log/mysqld.log
      - /var/lib/mysql
      - /etc/wsrep.cnf
    tags:
      - clean
