---
- hosts: pxc
  tasks: 
  - name: make pxc dir
    file:
      path: '{{ item }}'
      state: directory
      mode: 0755
    with_items:
      - '{{ pxc_dir }}'

  - name: install PXC
    yum: 
      name: Percona-XtraDB-Cluster-57
      state: present

  - name: enable PXC
    systemd:
      name: mysql
      state: started
      enabled: yes

  - name: change password
    shell: |
      init_password=`grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'`
      mysql -uroot -p"$init_password" --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ pxc_password }}'"
    register: shell_result

  - debug:
      var: shell_result.stdout_lines
